name: test_pt_seru
version: 1.0.0+1
publish_to: none
description: Application for recruitment process held by PT. Solusi Eksplorasi
  Rembulan Utama.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get: 4.6.6
  path_provider: ^2.1.2
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
